### ISSUE TITLE
'H2OFFT-Sx65.efi` is not recognized as an internal or external command, operable program, or script file

### ISSUE THREAD

**Issue by stefanfoulis** [ljrk0/Framework_Laptop_11th_Gen_Intel_Core_BIOS_3.19_EFI#1]
Thanks for this, I'm really looking forward to finally getting my firmware patched!

I tried it out on a USB-stick. After disabling Secure Boot and copying the contents of the downloaded zip file onto the FAT partition I was able to boot from it.
This is some of the output it shows:
![IMG_20240205_213702-obfuscated](https://github.com/ljrk0/Framework_Laptop_11th_Gen_Intel_Core_BIOS_3.19_EFI/assets/14330/47ac2a61-365f-4b83-acf6-d2d35ab8fdc9)

I don't know much about how this EFI shell works... so I'm probably just missing something obvious. I did naivly try changing the permissions of `H2OFFT-Sx65.efi` to be executable, but that didn't help.

**Comment by ljrk0** [comment]
Hey, glad to see people using it!

UEFI works similar to Windows (and VMS or Arc) in that it doesn't have a unified virtual root file system, but every device has its own volume. Unlike Windows, they aren't named C:\ etc., but FS0: or FS1: in your case.

The `Shell>` prompt indicates that you aren't "on" any volume yet, so you need to switch to the volume containing the files, from the README:

```
Shell> FS0:
FS0:\> .\shellx64.efi .\isflash.bin
```

If the files reside on FS1:, you need to type `FS1:` instead. You can always switch volumes or explore the files using `dir`/`ls` when you are inside one.

Hope this helps?

**Comment by ljrk0** [comment]
I will improve the README to point out what's happening in more detail with v1.1 :)

**Comment by ljrk0** [comment]
Oh, and in theory you shouldn't be dropped to the shell for the USB updater, tbqh.  To be sure: The files from inside `efi_root` (`startup.nsh` etc.) should be at the top level in the USB.

**Comment by stefanfoulis** [comment]
Thanks for the hints :bow: 
I was trying things like `cd /`, which of course didn't work.

These are the contents in the root of my USB drive:
```
├── efi
│   └── boot
│       └── bootx64.efi
├── FWUpdate.bin
├── FWUpdLcl.efi
├── H2OFFT-Sx64.efi
├── isflash.bin
└── startup.nsh
```

In your comment above you mention `shellx64.efi`, I don't have that file.

I was able to "cd" to `FS0:\` though.

I assume the command(s) that are meant to run automatically are what is in `startup.nsh`.

I tried directly running the command from there manually:

```
Shell> FS0:
FS0:\> H2OFFT-Sx65.efi isflash.bin
```
But that didn't work. Then I also tried it with:
```
FS0:\> H2OFFT-Sx65.efi -F isflash.bin
```
But that also yielded a (different) error.
I forgot to note the outputs :man_facepalming: . I'll try it again later and will add some more info.

**Comment by ljrk0** [comment]
Oof -- I'm sorry, I made two mistakes:

1. It's `H2OFFT-Sx64.efi`, notice the 4 instead of the 5 :'D
2. Above, where I wrote `shellx64.efi` should also have been `H2OFFT-Sx64.efi`

The x65-Typo was also what I mistyped in `startup.nsh`. I've fixed those in v1.1 but you can just use the correct name when invoking the flashing procedure instead of replacing the files :)

**Comment by stefanfoulis** [comment]
I tried again with your fixes and this time it worked. Thanks for the help @ljrk0 !

**Comment by stefanfoulis** [comment]
:heart: :partying_face: 
![Screenshot from 2024-02-06 19-49-53](https://github.com/ljrk0/Framework_Laptop_11th_Gen_Intel_Core_BIOS_3.19_EFI/assets/14330/b6362e65-4c9c-4a1a-b6bd-8f09dcb07990)

(Although that download from `mega.nz` does make me very nervous :sweat_smile: )

**Comment by ljrk0** [comment]
Amazing, glad it worked in the end!

While of course no real "cred", the files do look very legitimate and are of the same format that I recognize from legit redistributions by vendors, the Windows binaries also carry a legit intel signature -- so I wouldn't worry too much.  Also note:  If you didn't deactivate Secure Boot for flashing, this means all binaries that were run were checked by SB for a valid signature by Microsoft, including FWUpdLcl.efi!  This ain't perfect, but it's as close as we can get until Framework get's their shit together :)

**Comment by jcapp** [comment]
Kudos on this.  I use Linux exclusively and have been scratching my head on how to update the BIOS.  I ran into an issue where the updater would not run because I didn't have a battery installed. (screenshot) I was able to fix that by 'hexediting' isflash.bin and setting the flags to disable A/C and battery checks.  I'd be happy to send docs if interested.

![IMG_0896](https://github.com/ljrk0/Framework_Laptop_11th_Gen_Intel_Core_BIOS_3.19_EFI/assets/950260/e56f3844-6745-4539-ab8d-5560c24a6719)

Next I had an issue where the FwUpdLcl.efi command had multiple arguments (screenshot) I was also able to fix that by 'hexediting' isflash.bin and changing the arguments to '-allowsv', which also allowed by to run it a second time.

Finally, I am having an issue that I can't get past an error where it thinks the CSME update failed.  I even created a "Hello World" .efi binary and stubbed it over the FwUpdLcl.efi and I'm still getting this.


![IMG_0902](https://github.com/ljrk0/Framework_Laptop_11th_Gen_Intel_Core_BIOS_3.19_EFI/assets/950260/3ddb8945-055b-4006-a47a-c314e81b2c04)
Any ideas?

Thanks again for the great work!
